export const MESSAGE_ERROR = 'MESSAGE_ERROR';
export const MESSAGE_WARNING = 'MESSAGE_WARNING';
export const MESSAGE_INFO = 'MESSAGE_INFO';
export const MESSAGE_CLOSE = 'MESSAGE_CLOSE';
export const MESSAGE_SUCCESS = 'MESSAGE_SUCCESS';
export const LOADING = 'LOADING';
export const CONTAINER_SIZE = 'CONTAINER_SIZE';
